// <auto-generated />
using Microsoft.Phone.Controls;
 
namespace WebClientTest
{
    public partial class MainPage
    {
        private static string[] AllFilesInHTMLFolder()
        {
            return new[] {
                           "HTML/canvasjs.min.js",
                           "HTML/native.js",
                        };
        }
    }
}