#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("SQLiteSpeedTests.Resource", IsApplication=true)]

namespace SQLiteSpeedTests
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xamarin.Android.NUnitLite.Resource.Id.OptionHostName = global::SQLiteSpeedTests.Resource.Id.OptionHostName;
			global::Xamarin.Android.NUnitLite.Resource.Id.OptionPort = global::SQLiteSpeedTests.Resource.Id.OptionPort;
			global::Xamarin.Android.NUnitLite.Resource.Id.OptionRemoteServer = global::SQLiteSpeedTests.Resource.Id.OptionRemoteServer;
			global::Xamarin.Android.NUnitLite.Resource.Id.OptionsButton = global::SQLiteSpeedTests.Resource.Id.OptionsButton;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultFullName = global::SQLiteSpeedTests.Resource.Id.ResultFullName;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultMessage = global::SQLiteSpeedTests.Resource.Id.ResultMessage;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultResultState = global::SQLiteSpeedTests.Resource.Id.ResultResultState;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultStackTrace = global::SQLiteSpeedTests.Resource.Id.ResultStackTrace;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsFailed = global::SQLiteSpeedTests.Resource.Id.ResultsFailed;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsId = global::SQLiteSpeedTests.Resource.Id.ResultsId;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsIgnored = global::SQLiteSpeedTests.Resource.Id.ResultsIgnored;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsInconclusive = global::SQLiteSpeedTests.Resource.Id.ResultsInconclusive;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsMessage = global::SQLiteSpeedTests.Resource.Id.ResultsMessage;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsPassed = global::SQLiteSpeedTests.Resource.Id.ResultsPassed;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsResult = global::SQLiteSpeedTests.Resource.Id.ResultsResult;
			global::Xamarin.Android.NUnitLite.Resource.Id.RunTestsButton = global::SQLiteSpeedTests.Resource.Id.RunTestsButton;
			global::Xamarin.Android.NUnitLite.Resource.Id.TestSuiteListView = global::SQLiteSpeedTests.Resource.Id.TestSuiteListView;
			global::Xamarin.Android.NUnitLite.Resource.Layout.options = global::SQLiteSpeedTests.Resource.Layout.options;
			global::Xamarin.Android.NUnitLite.Resource.Layout.results = global::SQLiteSpeedTests.Resource.Layout.results;
			global::Xamarin.Android.NUnitLite.Resource.Layout.test_result = global::SQLiteSpeedTests.Resource.Layout.test_result;
			global::Xamarin.Android.NUnitLite.Resource.Layout.test_suite = global::SQLiteSpeedTests.Resource.Layout.test_suite;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.ApplicationName = global::SQLiteSpeedTests.Resource.String.ApplicationName;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.Hello = global::SQLiteSpeedTests.Resource.String.Hello;
			global::SimplyMobile.Data.Resource.String.library_name = global::SQLiteSpeedTests.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int monoandroidsplash = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060001
			public const int OptionHostName = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int OptionPort = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int OptionRemoteServer = 2131099648;
			
			// aapt resource value: 0x7f06000f
			public const int OptionsButton = 2131099663;
			
			// aapt resource value: 0x7f06000a
			public const int ResultFullName = 2131099658;
			
			// aapt resource value: 0x7f06000c
			public const int ResultMessage = 2131099660;
			
			// aapt resource value: 0x7f06000b
			public const int ResultResultState = 2131099659;
			
			// aapt resource value: 0x7f06000d
			public const int ResultStackTrace = 2131099661;
			
			// aapt resource value: 0x7f060006
			public const int ResultsFailed = 2131099654;
			
			// aapt resource value: 0x7f060003
			public const int ResultsId = 2131099651;
			
			// aapt resource value: 0x7f060007
			public const int ResultsIgnored = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int ResultsInconclusive = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int ResultsMessage = 2131099657;
			
			// aapt resource value: 0x7f060005
			public const int ResultsPassed = 2131099653;
			
			// aapt resource value: 0x7f060004
			public const int ResultsResult = 2131099652;
			
			// aapt resource value: 0x7f06000e
			public const int RunTestsButton = 2131099662;
			
			// aapt resource value: 0x7f060010
			public const int TestSuiteListView = 2131099664;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int options = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int results = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int test_result = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int test_suite = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int ApplicationName = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int Hello = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Mono_Android_Theme_Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
